# This file contains some common settings that would be customized and used for a first installation.
#
# Be sure to also check the 'values-secure-data.yaml' file for more settings.
#
# The contents of this file can be added to your own custom values.yaml file.
#

# Pin to a specific Code Dx version
codedxTomcatImage: codedx/codedx-tomcat:v3.6.1

# Keep or modify Code Dx app data storage size
persistence:
  size: 32Gi

# Provide a pre-existing Code Dx license secret - it's better to make a secret before-hand
# than have the chart auto-create one, since that would require having the license file
# with your values file.
license:
  # The 'codedx-license' secret should be in the same namespace as Code Dx, and have
  # a key named 'license.lic' with the license to use.
  secret: codedx-license

# Keep or modify existing MariaDB storage settings - but the passwords should be changed!
mariadb:
  rootUser:
    password: CHANGEME-1!
  replication:
    password: CHANGEME-2!
  master:
    persistence:
      size: 32Gi
  slave:
    persistence:
      size: 32Gi