apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codedx.adminSecretName" . | quote }}
  labels:
    {{- include "codedx.commonLabels" . | nindent 4 }}
type: Opaque
data:
  password: {{ default (randAlphaNum 16) .Values.codedxAdminPassword | b64enc | quote }}