{{- if .Values.cacertsFile -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codedx.cacerts.secretName" . | quote }}
  labels:
    {{- include "codedx.commonLabels" . | nindent 4 }}
type: Opaque
data:
  cacerts: {{ .Files.Get .Values.cacertsFile | b64enc | quote }}
{{- end -}}