apiVersion: v1
name: codedx
version: 0.4.0
kubeVersion: ">=1.8.0"
appVersion: "3.7.0"
description: A Helm chart for Code Dx
icon: https://codedx.com/wp-content/uploads/2017/03/CodeDx-logo.png
home: https://github.com/codedx/codedx-kubernetes
keywords:
- codedx
- security
- sast
- scan
- analysis
sources:
- https://hub.docker.com/r/codedx/codedx-tomcat
- https://hub.docker.com/_/tomcat/
- https://hub.docker.com/r/bitnami/mariadb
maintainers:
- name: Code Dx, Inc.
  email: support@codedx.com