{{- if .Values.master.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "master.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: "{{ template "mariadb.name" . }}"
    component: "master"
    chart: "{{ template "mariadb.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  my.cnf: |-
{{ .Values.master.config | indent 4 }}
{{- if .Values.master.masterTlsSecret }}
    [mysqld]
    ssl_cert=/mariadb/tls/cert/tls.crt
    ssl_key=/mariadb/tls/cert/tls.key
{{- end }}
{{- if .Values.master.masterCaConfigMap }}
    [mysqld]
    ssl_ca=/mariadb/tls/ca/ca.crt
{{- end }}
{{- end -}}
