{{- if .Values.master.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "mariadb.fullname" . }}
  labels:
    app: "{{ template "mariadb.name" . }}"
    component: "master"
    chart: {{ template "mariadb.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
{{- $minAvailable := .Values.master.podDisruptionBudget.minAvailable -}}
{{- $maxUnavailable := .Values.master.podDisruptionBudget.maxUnavailable -}}
{{- if kindIs "int64" $minAvailable }}   {{/* use kindIs to distinguish between an empty value and 0 */}}
  minAvailable: {{ $minAvailable }}
{{- end }}
{{- if kindIs "int64" $maxUnavailable }} {{/* use kindIs to distinguish between an empty value and 0 */}}
  maxUnavailable: {{ $maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
      app: "{{ template "mariadb.name" . }}"
      component: "master"
      release: {{ .Release.Name | quote }}
{{- end }}
