{{- if .Values.master.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "mariadb.fullname" . }}
  labels:
    app: "{{ template "mariadb.name" . }}"
    component: "master"
    chart: {{ template "mariadb.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
{{- $minAvailable := .Values.master.podDisruptionBudget.minAvailable -}}
{{- $maxUnavailable := .Values.master.podDisruptionBudget.maxUnavailable -}}

{{- if or (kindIs "int64" $minAvailable) (kindIs "float64" $minAvailable) }}     {{/* use kindIs to distinguish between an empty value and 0 */}}
  minAvailable: {{ $minAvailable }}
{{- else if $minAvailable }}  
  minAvailable: {{ $minAvailable | quote }}
{{- end }}

{{- if or (kindIs "int64" $maxUnavailable) (kindIs "float64" $maxUnavailable) }} {{/* use kindIs to distinguish between an empty value and 0 */}}
  maxUnavailable: {{ $maxUnavailable }}
{{- else if $maxUnavailable }}  
  maxUnavailable: {{ $maxUnavailable | quote }}
{{- end }}
  selector:
    matchLabels:
      app: "{{ template "mariadb.name" . }}"
      component: "master"
      release: {{ .Release.Name | quote }}
{{- end }}
